In [2]:
from sklearn.datasets import load_iris

In [13]:
from sklearn.model_selection import train_test_split

In [17]:
from sklearn.model_selection import StratifiedShuffleSplit

In [5]:
import numpy as np
import pandas as pd

In [3]:
data = load_iris()

### iris 데이터셋

In [7]:
data.data.shape

(150, 4)

In [56]:
data.target.shape

(150,)

## train_test spllit 안쓸 경우

In [51]:
split = StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=1004) 


In [52]:
for train_idx, test_idx in split.split(data.data , data.target):
    x_train = data.data[train_idx]
    y_train = data.target[train_idx]
    x_test = data.data[test_idx]
    y_test = data.target[test_idx]

### ridge, lasso

In [57]:
from sklearn.linear_model import Ridge

In [58]:
ridge_reg = Ridge(alpha =1 , solver= "cholesky")

In [60]:
ridge_reg.fit(x_train,y_train)

Ridge(alpha=1, solver='cholesky')

In [64]:
ridge_reg.predict([[4.7, 3.2, 1.3, 0.2]])

array([-0.05343177])

### Logistic

In [65]:
from sklearn.linear_model import LogisticRegression

In [70]:
log_reg = LogisticRegression(multi_class='multinomial', solver = 'lbfgs' , C = 10)

In [71]:
log_reg.fit(x_train ,y_train)

/opt/homebrew/Caskroom/miniforge/base/envs/jupyter/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(C=10, multi_class='multinomial')

In [76]:
log_reg.predict(x_test)

array([1, 0, 0, 0, 0, 2, 1, 0, 1, 2, 1, 1, 0, 0, 0, 0, 2, 1, 2, 1, 2, 2,
       0, 2, 2, 2, 2, 1, 1, 1])

In [75]:
y_test

array([1, 0, 0, 0, 0, 2, 1, 0, 1, 2, 1, 1, 0, 0, 0, 0, 2, 1, 2, 1, 2, 2,
       0, 2, 2, 2, 1, 2, 1, 1])

## 앙상블

In [78]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import VotingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC

In [81]:
log_clf = LogisticRegression(multi_class='multinomial', solver = 'lbfgs' , C = 10)
rnd_clf = RandomForestClassifier()
svm_clf = SVC()

In [82]:
voting_clf = VotingClassifier(
    estimators= [('lr',log_clf), ('rf',rnd_clf), ('svc',svm_clf)],
    voting = 'hard'
)


In [84]:
voting_clf.fit(x_train,y_train)

/opt/homebrew/Caskroom/miniforge/base/envs/jupyter/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


VotingClassifier(estimators=[('lr',
                              LogisticRegression(C=10,
                                                 multi_class='multinomial')),
                             ('rf', RandomForestClassifier()), ('svc', SVC())])

In [85]:
from sklearn.metrics import accuracy_score

In [86]:
for clf in (log_clf ,rnd_clf, svm_clf, voting_clf):
    clf.fit(x_train ,y_train)
    y_pred = clf.predict(x_test)
    print(clf.__class__.__name__ , accuracy_score(y_test, y_pred))

LogisticRegression 0.9333333333333333
RandomForestClassifier 0.9333333333333333
SVC 0.9333333333333333
VotingClassifier 0.9333333333333333


/opt/homebrew/Caskroom/miniforge/base/envs/jupyter/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/opt/homebrew/Caskroom/miniforge/base/envs/jupyter/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-

### xgboost 

In [89]:
from xgboost import XGBClassifier

In [90]:
model = XGBClassifier(n_estimators=100, learning_rate=0.1, max_depth=4, random_state = 32)

In [91]:
model.fit(x_train ,y_train)

XGBClassifier(base_score=0.5, booster='gbtree', callbacks=None,
              colsample_bylevel=1, colsample_bynode=1, colsample_bytree=1,
              early_stopping_rounds=None, enable_categorical=False,
              eval_metric=None, gamma=0, gpu_id=-1, grow_policy='depthwise',
              importance_type=None, interaction_constraints='',
              learning_rate=0.1, max_bin=256, max_cat_to_onehot=4,
              max_delta_step=0, max_depth=4, max_leaves=0, min_child_weight=1,
              missing=nan, monotone_constraints='()', n_estimators=100,
              n_jobs=0, num_parallel_tree=1, objective='multi:softprob',
              predictor='auto', random_state=32, reg_alpha=0, ...)

In [93]:
y_pred = model.predict(x_test) 

In [94]:
y_pred

array([1, 0, 0, 0, 0, 2, 1, 0, 1, 2, 1, 1, 0, 0, 0, 0, 2, 1, 2, 1, 2, 2,
       0, 2, 2, 2, 2, 1, 1, 1])

In [96]:
y_test

array([1, 0, 0, 0, 0, 2, 1, 0, 1, 2, 1, 1, 0, 0, 0, 0, 2, 1, 2, 1, 2, 2,
       0, 2, 2, 2, 1, 2, 1, 1])

### LightGbm

In [ ]:
from lightgbm import LGBMClassifier