In [25]:
from LDAVI import LDAVI
import os
import codecs

In [26]:
document_file_path = "./data/ap.dat"
voca_file_path = "./data/vocab.txt"
output_dir_name = "./output_LDA_VI/"
topics = 50
iterations = 100


In [27]:
os.makedirs(output_dir_name, exist_ok=True)

In [28]:
def read_voca_file(file_path):
    """
    Read vocabulary file
    :param file_path: The path of vocabulary file
    :return: vocabulary list
    """
    vocas = list()

    with codecs.open(file_path, "r", "utf-8") as voca_file:
        for each_line in voca_file:
            vocas.append(each_line.strip())

    return vocas

In [29]:
vocas = read_voca_file(voca_file_path)

In [30]:
vocas

['i',
 'new',
 'percent',
 'people',
 'year',
 'two',
 'million',
 'president',
 'last',
 'government',
 'years',
 'first',
 'police',
 'state',
 'states',
 'officials',
 'soviet',
 'united',
 'bush',
 'time',
 'three',
 'billion',
 'today',
 'national',
 'told',
 'american',
 'thursday',
 'federal',
 'house',
 'week',
 'court',
 'day',
 'tuesday',
 'made',
 'news',
 'wednesday',
 'monday',
 'friday',
 'say',
 'company',
 'city',
 'party',
 'just',
 'group',
 'york',
 'market',
 'report',
 'department',
 'military',
 'south',
 'union',
 'members',
 'home',
 'west',
 'political',
 'reported',
 'make',
 'going',
 'office',
 'get',
 'spokesman',
 'dont',
 'world',
 'like',
 'four',
 'think',
 'committee',
 'back',
 'work',
 'defense',
 'says',
 'country',
 'war',
 'congress',
 'nations',
 'foreign',
 'official',
 'public',
 'trade',
 'take',
 'prices',
 'month',
 'general',
 'economic',
 'five',
 'air',
 'money',
 'stock',
 'called',
 'found',
 'dukakis',
 'days',
 'campaign',
 'law',
 'm

In [31]:
LDA_Model = LDAVI(topics, document_file_path, vocas, output_dir_name)

In [32]:
print(LDA_Model._K)
print(LDA_Model._words)


50
['i', 'new', 'percent', 'people', 'year', 'two', 'million', 'president', 'last', 'government', 'years', 'first', 'police', 'state', 'states', 'officials', 'soviet', 'united', 'bush', 'time', 'three', 'billion', 'today', 'national', 'told', 'american', 'thursday', 'federal', 'house', 'week', 'court', 'day', 'tuesday', 'made', 'news', 'wednesday', 'monday', 'friday', 'say', 'company', 'city', 'party', 'just', 'group', 'york', 'market', 'report', 'department', 'military', 'south', 'union', 'members', 'home', 'west', 'political', 'reported', 'make', 'going', 'office', 'get', 'spokesman', 'dont', 'world', 'like', 'four', 'think', 'committee', 'back', 'work', 'defense', 'says', 'country', 'war', 'congress', 'nations', 'foreign', 'official', 'public', 'trade', 'take', 'prices', 'month', 'general', 'economic', 'five', 'air', 'money', 'stock', 'called', 'found', 'dukakis', 'days', 'campaign', 'law', 'months', 'program', 'case', 'asked', 'workers', 'administration', 'late', 'business', 'east'

In [33]:
print(LDA_Model._docs)

[<LDAVI.LDAVI.Document object at 0x7ff6402f2e50>, <LDAVI.LDAVI.Document object at 0x7ff6401695b0>, <LDAVI.LDAVI.Document object at 0x7ff6205d9460>, <LDAVI.LDAVI.Document object at 0x7ff6205d9a30>, <LDAVI.LDAVI.Document object at 0x7ff6205d9dc0>, <LDAVI.LDAVI.Document object at 0x7ff6205d9c10>, <LDAVI.LDAVI.Document object at 0x7ff6205d9670>, <LDAVI.LDAVI.Document object at 0x7ff6205d9df0>, <LDAVI.LDAVI.Document object at 0x7ff6205d9430>, <LDAVI.LDAVI.Document object at 0x7ff6205d9040>, <LDAVI.LDAVI.Document object at 0x7ff6205d9ac0>, <LDAVI.LDAVI.Document object at 0x7ff6205d9070>, <LDAVI.LDAVI.Document object at 0x7ff6205d9a90>, <LDAVI.LDAVI.Document object at 0x7ff6205d9310>, <LDAVI.LDAVI.Document object at 0x7ff6205d92b0>, <LDAVI.LDAVI.Document object at 0x7ff6205d9220>, <LDAVI.LDAVI.Document object at 0x7ff6205d9e80>, <LDAVI.LDAVI.Document object at 0x7ff6205d9eb0>, <LDAVI.LDAVI.Document object at 0x7ff6205d94f0>, <LDAVI.LDAVI.Document object at 0x7ff6205d9ca0>, <LDAVI.LDAVI.Docume

In [34]:
LDA_Model._lambda.shape

(50, 10473)

In [35]:
print(LDA_Model._Elogbeta.shape)

(50, 10473)


In [151]:
LDA_Model._alpha

0.1

In [45]:
# print(LDA_Model._W) # 10473. 단어수
# print(LDA_Model._D) # 2246 문서수
# print(LDA_Model._alpha) # alpha =0.1 
# print(LDA_Model._eta) # eta =0.01
# print(LDA_Model._small_num) # small num
# print(LDA_Model._lambda) # LDA_Model._lambda.shape  (50, 10473)  K W
# print(LDA_Model._Elogbeta) # 람다에 elogbeta 쒸운거임 
# print(LDA_Model._expElogbeta) # 위에꺼에 exp 취한거임 
# print(LDA_Model._gamma) # LDA_Model._gamma.shape( 2246 , 50)  DK 




10473
2246
0.1
0.01
1e-100
[[1.15225311 0.96830122 1.12759267 ... 0.89179713 0.87825082 0.80311529]
 [0.91163879 0.91593018 1.06477736 ... 0.86003509 0.8518114  1.08747324]
 [1.07536684 1.10900501 0.93594654 ... 0.81653022 0.90851313 0.99888891]
 ...
 [0.86943624 0.94714644 1.05755883 ... 0.91956244 0.98174056 1.02565619]
 [1.00876006 1.106121   0.89493739 ... 1.15550156 0.97128553 1.0929211 ]
 [0.97686621 1.05964884 1.00831726 ... 1.03270365 1.1299291  1.08564046]]
[[ -9.60933276  -9.88863505  -9.64293315 ... -10.0288395  -10.05554857
  -10.21590004]
 [ -9.98845788  -9.98039297  -9.73112075 ... -10.09011891 -10.10717315
   -9.69754971]
 [ -9.71437171  -9.66565683  -9.94254813 ... -10.18232551  -9.99340899
   -9.83377865]
 ...
 [-10.07231275  -9.92476492  -9.74340437 ...  -9.97500049  -9.86474108
   -9.79286869]
 [ -9.81866974  -9.6707887  -10.02047354 ...  -9.6027212   -9.88123883
   -9.6897203 ]
 [ -9.87224518  -9.7394758   -9.8199358  ...  -9.78098819  -9.63799057
   -9.70084956]]
[

In [37]:
Elogtheta = LDA_Model._dirichlet_expectation(LDA_Model._gamma)

In [38]:
Elogtheta.shape

(2246, 50)

In [39]:
import numpy

In [40]:
sstats = numpy.zeros(LDA_Model._lambda.shape)

In [16]:
sstats.shape

(50, 10473)

In [17]:
LDA_Model._lambda.shape

(50, 10473)

In [ ]:
Elogtheta = self._dirichlet_expectation(self._gamma)
expElogtheta = numpy.exp(Elogtheta) # ( 2246 ,50 )    DK
sstats = numpy.zeros(self._lambda.shape) # (50 ,10473 )  KW
print(sstats.shape)
for doc_idx, doc in enumerate(self._docs):
    print(doc_idx,doc)

    ids = doc.wordids
    cts = doc.wordcts
    print('@@@@@@@@@@@@@@')

    gammad = self._gamma[doc_idx, :]
    print(gammad)
    expElogthetad = expElogtheta[doc_idx, :]
    expElogbetad = self._expElogbeta[:, ids]
    for _ in range(e_max_iter):
        lastgamma = gammad
       # sstats=numpy.matmul(expElogthetad, expElogbetad)      


        # Update phi and gamma of d-th document

# 원본

In [41]:
Elogtheta = LDA_Model._dirichlet_expectation(LDA_Model._gamma) #.  (2246, 50) DK
expElogtheta = numpy.exp(Elogtheta) # ( 2246 ,50 )    DK
sstats = numpy.zeros(LDA_Model._lambda.shape) # (50 ,10473 )  KW

In [42]:
for doc_idx, doc in enumerate(LDA_Model._docs):
    ids = doc.wordids  
    cts = doc.wordcts
    gammad = LDA_Model._gamma[doc_idx, :]
    expElogthetad = expElogtheta[doc_idx, :]
    expElogbetad = LDA_Model._expElogbeta[:, ids]
    break

In [44]:
sstats.shape

(50, 10473)

In [23]:
len(ids)

186

In [21]:
gammad

array([1.09655993, 1.08073226, 0.96070488, 1.10537466, 0.92372943,
       0.96561836, 0.91160381, 0.82881818, 0.96899195, 0.78714001,
       1.04349046, 1.06779177, 1.03355771, 1.18501958, 1.22388019,
       0.8846177 , 0.96274488, 1.01952798, 1.1592896 , 1.01619282,
       1.05183117, 0.91623853, 1.07045826, 1.01164872, 0.96862531,
       0.93693794, 0.93363622, 1.05504615, 0.86337086, 0.9438518 ,
       0.92325104, 0.87690065, 0.86741066, 1.14009118, 0.93816779,
       1.18593571, 0.93177729, 1.11613014, 0.93526654, 0.89904296,
       0.89606139, 1.09354692, 0.99251006, 1.06865357, 0.9624115 ,
       0.90827752, 0.7486983 , 0.97351747, 1.14091491, 1.0669043 ])

In [24]:
expElogthetad

array([0.01325424, 0.01295253, 0.01068922, 0.01342254, 0.01000242,
       0.0107809 , 0.00977847, 0.00826882, 0.0108439 , 0.00752373,
       0.01224538, 0.01270637, 0.01205747, 0.01495163, 0.01570258,
       0.00928248, 0.01072727, 0.01179257, 0.01445609, 0.01172969,
       0.01240341, 0.00986399, 0.01275706, 0.01164408, 0.01083705,
       0.01024711, 0.01018588, 0.01246437, 0.00889452, 0.01037549,
       0.00999357, 0.0091413 , 0.0089681 , 0.01408728, 0.01026993,
       0.0149693 , 0.01015142, 0.01362817, 0.01021611, 0.00954718,
       0.00949238, 0.01319675, 0.01128427, 0.01272275, 0.01072105,
       0.00971715, 0.0068472 , 0.01092848, 0.01410309, 0.0126895 ])

In [55]:
len(ids)

186

In [51]:
expElogbetad.shape

(50, 186)

In [50]:
expElogthetad.shape

(50,)

In [ ]:
def _dirichlet_expectation(alpha):
        """
        Compute E[log(theta)] given alpha
        Compute E[log(beta)] given lambda
        Do not modify this function
        :param alpha: alpha value or lambda value
        :return: E[log(theta)] or E[log(beta)]
        """
        if 1 == len(alpha.shape):
            return scipy.special.psi(alpha) - scipy.special.psi(numpy.sum(alpha))
        return scipy.special.psi(alpha) - scipy.special.psi(numpy.sum(alpha, 1))[:, numpy.newaxis]


In [ ]:
def _e_step(self, e_max_iter, meanchangethresh):
        """
        Run E step in variational EM
        Update phi and gamma and
        Compute sufficient statistics for updating lambda (sstats) for M step
        :param e_max_iter: maximum iterations for e step
        :param meanchangethresh: minimum value for checking convergence
        :return: sufficient statistics for updating lambda
        """
        Elogtheta = self._dirichlet_expectation(self._gamma)
        expElogtheta = numpy.exp(Elogtheta) # ( 2246 ,50 )    DK
        sstats = numpy.zeros(self._lambda.shape) # (50 ,10473 )  KW

        for doc_idx, doc in enumerate(self._docs):
            ids = doc.wordids   # word index가 붙어있음  186
            cts = doc.wordcts   # word index에 대한 카운츠가 붙어있음 
            gammad = self._gamma[doc_idx, :]  # D에 대한 감마값 (50,) 토픽에 대한 값임  
            expElogthetad = expElogtheta[doc_idx, :] # 세타  (50,) 세타는 토픽에 관련한 값 
            expElogbetad = self._expElogbeta[:, ids] # (50 ,186) K W  뿌사이임 이게 

            for _ in range(e_max_iter):
                lastgamma = gammad

                # Update phi and gamma of d-th document
                pass

                meanchange = numpy.mean(abs(gammad - lastgamma))
                if meanchange < meanchangethresh:
                    break
            self._gamma[doc_idx, :] = gammad

        # Compute sufficient statistics for updating lambda (sstats) for M step
        pass

        return sstats

In [ ]:
def _e_step(self, e_max_iter, meanchangethresh):
    """
    Run E step in variational EM
    Update phi and gamma and
    Compute sufficient statistics for updating lambda (sstats) for M step
    :param e_max_iter: maximum iterations for e step
    :param meanchangethresh: minimum value for checking convergence
    :return: sufficient statistics for updating lambda
    """
    Elogtheta = self._dirichlet_expectation(self._gamma)
    expElogtheta = numpy.exp(Elogtheta) # ( 2246 ,50 )    DK
    sstats = numpy.zeros(self._lambda.shape) # (50 ,10473 )  KW

    for doc_idx, doc in enumerate(self._docs):
        ids = doc.wordids   # word index가 붙어있음  186
        cts = doc.wordcts   # word index에 대한 카운츠가 붙어있음 
        gammad = self._gamma[doc_idx, :]  # D에 대한 감마값 (50,) 토픽에 대한 값임  
        expElogthetad = expElogtheta[doc_idx, :] # 세타  (50,) 세타는 토픽에 관련한 값 
        expElogbetad = self._expElogbeta[:, ids] # (50 ,186) K W  뿌사이임 이게 

        for _ in range(e_max_iter):
            lastgamma = gammad
            for words_in_docu in ids:
                phi_words_in_docu=[]
                for topic in range(50):
                    phi_words_in_docu.append()



            # Update phi and gamma of d-th document
            pass

            meanchange = numpy.mean(abs(gammad - lastgamma))
            if meanchange < meanchangethresh:
                break
        self._gamma[doc_idx, :] = gammad

    # Compute sufficient statistics for updating lambda (sstats) for M step
    pass

    return sstats

In [179]:
words_phi_weighted.T

(50, 186)

In [182]:
sstats[:,ids]=sstats[:,ids]+words_phi_weighted.T

In [185]:
sstats

array([[0.02478591, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.0171353 , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.01839186, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.01518788, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.02165227, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.02867296, 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [157]:
sstats.shape

(50, 10473)

In [161]:
LDA_Model._lambda.shape

(50, 10473)

In [154]:
gammad

array([0.9828841 , 0.98883235, 0.87747871, 0.93410392, 1.04711965,
       1.00059088, 0.91856207, 1.05525134, 1.05921315, 1.08173664,
       1.05313613, 1.0354431 , 0.96376397, 0.85911879, 0.87957096,
       0.86997253, 0.85440701, 0.85112887, 1.02598489, 0.92692932,
       1.04972536, 1.0951156 , 1.08553816, 1.1375705 , 1.10883061,
       0.94287612, 1.06414949, 0.90547679, 0.9841623 , 1.02332953,
       0.98636875, 1.04816424, 1.0768472 , 0.9534618 , 1.0299278 ,
       0.94274067, 0.93629924, 0.85093187, 1.00198336, 1.14447275,
       1.19308523, 0.96455354, 1.14052994, 0.92625333, 1.00306714,
       0.92624256, 0.78453939, 0.96718659, 1.02832993, 1.27568013])

In [190]:
Elogtheta = LDA_Model._dirichlet_expectation(LDA_Model._gamma)
expElogtheta = numpy.exp(Elogtheta) # ( 2246 ,50 )    DK
sstats = numpy.zeros(LDA_Model._lambda.shape) # (50 ,10473 )  KW

for doc_idx, doc in enumerate(LDA_Model._docs):
    ids = doc.wordids   # word index가 붙어있음  186
    cts = doc.wordcts   # word index에 대한 카운츠가 붙어있음 
    gammad = LDA_Model._gamma[doc_idx, :]  # D에 대한 감마값 (50,) 토픽에 대한 값임  
    expElogthetad = expElogtheta[doc_idx, :] # 세타  (50,) 세타는 토픽에 관련한 값 
    expElogbetad = LDA_Model._expElogbeta[:, ids] # (50 ,186) K W  뿌사이임 이게 
    for _ in range(2000):
        lastgamma = gammad
        words_phi=expElogthetad.reshape(-1,1) * expElogbetad
        # normalization phi for each word
        sum_of_phis_for_each_words= words_phi.sum(axis=0)
        words_phi_normalization= (words_phi/sum_of_phis_for_each_words).T # 제가 가로세로 헷갈려서 뒤집어놓습니다;;
        words_phi_weighted=numpy.array(cts).reshape(-1,1)*words_phi_normalization
        sum_of_pih_50 = LDA_Model._alpha + numpy.sum(words_phi_weighted,axis=0)
        gammad =  sum_of_pih_50
        
        meanchange = numpy.mean(abs(gammad - lastgamma))
        if meanchange < 100:
            break
        break
    self._gamma[doc_idx, :] = gammad
    # for문이 도는동안 sstat을 게속 더해주는게 훨씬 나을 것같아 for 문 안에 작성하였습니다.
    sstats[:,ids]=sstats[:,ids]+words_phi_weighted.T
    break    
        
        
        
            
#         
#             phi_words_in_docu=[]
#             for topic in range(50):
#                 phi_words_in_docu.append()
     

In [192]:
sstats.shape

(50, 10473)

In [171]:
sstats.shape

(50, 10473)

In [174]:
sstats

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [173]:
words_phi_weighted.T

array([[0.02478591, 0.01353489, 0.03475081, ..., 0.02444149, 0.01475051,
        0.02098804],
       [0.0171353 , 0.01901977, 0.03877138, ..., 0.0209556 , 0.01951777,
        0.02680192],
       [0.01839186, 0.0215697 , 0.03063427, ..., 0.01589622, 0.01329023,
        0.01630079],
       ...,
       [0.01518788, 0.01872332, 0.03193873, ..., 0.01654871, 0.02083609,
        0.01452898],
       [0.02165227, 0.00889836, 0.05173069, ..., 0.02470598, 0.01959568,
        0.01593232],
       [0.02867296, 0.0264817 , 0.04611285, ..., 0.03190879, 0.02739895,
        0.02748746]])

In [172]:
words_phi_weighted.T.shape

(50, 186)

In [165]:
lastgamma

array([0.9828841 , 0.98883235, 0.87747871, 0.93410392, 1.04711965,
       1.00059088, 0.91856207, 1.05525134, 1.05921315, 1.08173664,
       1.05313613, 1.0354431 , 0.96376397, 0.85911879, 0.87957096,
       0.86997253, 0.85440701, 0.85112887, 1.02598489, 0.92692932,
       1.04972536, 1.0951156 , 1.08553816, 1.1375705 , 1.10883061,
       0.94287612, 1.06414949, 0.90547679, 0.9841623 , 1.02332953,
       0.98636875, 1.04816424, 1.0768472 , 0.9534618 , 1.0299278 ,
       0.94274067, 0.93629924, 0.85093187, 1.00198336, 1.14447275,
       1.19308523, 0.96455354, 1.14052994, 0.92625333, 1.00306714,
       0.92624256, 0.78453939, 0.96718659, 1.02832993, 1.27568013])

In [166]:
gammad

array([0.9828841 , 0.98883235, 0.87747871, 0.93410392, 1.04711965,
       1.00059088, 0.91856207, 1.05525134, 1.05921315, 1.08173664,
       1.05313613, 1.0354431 , 0.96376397, 0.85911879, 0.87957096,
       0.86997253, 0.85440701, 0.85112887, 1.02598489, 0.92692932,
       1.04972536, 1.0951156 , 1.08553816, 1.1375705 , 1.10883061,
       0.94287612, 1.06414949, 0.90547679, 0.9841623 , 1.02332953,
       0.98636875, 1.04816424, 1.0768472 , 0.9534618 , 1.0299278 ,
       0.94274067, 0.93629924, 0.85093187, 1.00198336, 1.14447275,
       1.19308523, 0.96455354, 1.14052994, 0.92625333, 1.00306714,
       0.92624256, 0.78453939, 0.96718659, 1.02832993, 1.27568013])

In [164]:
words_phi_weighted.shape

(186, 50)

In [158]:
sstats.shape

(50, 10473)

In [145]:
words_phi_weighted.shape

(186, 50)

In [148]:
numpy.sum(words_phi_weighted,axis=0)

array([5.07863042, 5.08876869, 4.21971879, 4.68046703, 5.71582302,
       5.25373688, 4.56811263, 5.95871761, 5.81426672, 5.89824604,
       5.64334846, 5.67119694, 4.88425385, 4.13613301, 4.24217473,
       4.01858987, 4.05495944, 4.06490751, 5.43358749, 4.70703315,
       5.7343131 , 6.16947502, 6.05073549, 6.6187615 , 6.1722606 ,
       4.85359519, 5.84265656, 4.52392292, 5.06252649, 5.49595363,
       5.14063371, 5.60350122, 5.70128963, 4.93684574, 5.59638403,
       4.82518969, 4.78246247, 4.14089225, 5.34567454, 6.49644973,
       6.97317001, 5.03167062, 6.55480297, 4.56277404, 5.31840834,
       4.554055  , 3.48075145, 5.0579239 , 5.61757541, 7.62267246])

In [153]:
sum_of_pih_50

array([5.17863042, 5.18876869, 4.31971879, 4.78046703, 5.81582302,
       5.35373688, 4.66811263, 6.05871761, 5.91426672, 5.99824604,
       5.74334846, 5.77119694, 4.98425385, 4.23613301, 4.34217473,
       4.11858987, 4.15495944, 4.16490751, 5.53358749, 4.80703315,
       5.8343131 , 6.26947502, 6.15073549, 6.7187615 , 6.2722606 ,
       4.95359519, 5.94265656, 4.62392292, 5.16252649, 5.59595363,
       5.24063371, 5.70350122, 5.80128963, 5.03684574, 5.69638403,
       4.92518969, 4.88246247, 4.24089225, 5.44567454, 6.59644973,
       7.07317001, 5.13167062, 6.65480297, 4.66277404, 5.41840834,
       4.654055  , 3.58075145, 5.1579239 , 5.71757541, 7.72267246])

In [132]:
words_phi_normalization.shape


(186, 50)

In [139]:
g=numpy.array(cts).reshape(-1,1)*words_phi_normalization

In [140]:
g.shape

(186, 50)

In [134]:
cts

[1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 7,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 3,
 1,
 3,
 2,
 1,
 1,
 2,
 2,
 1,
 1,
 1,
 2,
 2,
 1,
 1,
 2,
 4,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 3,
 1,
 2,
 2,
 1,
 1,
 1,
 1,
 7,
 2,
 2,
 1,
 2,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 3,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 5,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 3,
 1,
 4,
 2,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 7,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 5,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 4,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1]

In [123]:
words_phi_normalization.shape


(50, 186)

In [106]:
print(words_phi.shape)
words_phi

(50, 186)


array([[7.42036857e-07, 4.11896984e-07, 5.28260342e-07, ...,
        7.28611274e-07, 4.41807895e-07, 6.35449700e-07],
       [5.12994183e-07, 5.78814325e-07, 5.89378655e-07, ...,
        6.24695509e-07, 5.84597176e-07, 8.11475227e-07],
       [5.50612785e-07, 6.56414465e-07, 4.65683323e-07, ...,
        4.73872989e-07, 3.98069558e-07, 4.93535176e-07],
       ...,
       [4.54692543e-07, 5.69792712e-07, 4.85512902e-07, ...,
        4.93324047e-07, 6.24083490e-07, 4.39890357e-07],
       [6.48222631e-07, 2.70797008e-07, 7.86378148e-07, ...,
        7.36495718e-07, 5.86930838e-07, 4.82378920e-07],
       [8.58406952e-07, 8.05897731e-07, 7.00979081e-07, ...,
        9.51214641e-07, 8.20654509e-07, 8.32231066e-07]])

In [101]:
words_phi.shape

(50, 186)

In [108]:
sum_of_phis_for_each_words=words_phi.sum(axis=0)

In [ ]:
words_phi/sum_of_phis_for_each_words

In [110]:
sum_of_phis_for_each_words.reshape(-1,1)

array([[2.99378554e-05],
       [3.04322467e-05],
       [3.04027679e-05],
       [3.04970750e-05],
       [3.00733928e-05],
       [3.07236838e-05],
       [2.98393436e-05],
       [2.95931059e-05],
       [2.96881133e-05],
       [3.07354911e-05],
       [3.12501392e-05],
       [3.13653999e-05],
       [3.10601444e-05],
       [3.02467442e-05],
       [3.05826467e-05],
       [3.17763537e-05],
       [3.10773111e-05],
       [3.05950223e-05],
       [3.14698740e-05],
       [3.11485076e-05],
       [3.05539237e-05],
       [3.06596878e-05],
       [3.04810720e-05],
       [3.03321469e-05],
       [3.00464867e-05],
       [3.01578586e-05],
       [3.00392902e-05],
       [2.94395421e-05],
       [3.09592521e-05],
       [3.06240478e-05],
       [3.01527758e-05],
       [3.12187159e-05],
       [3.14819102e-05],
       [3.01432435e-05],
       [3.09032752e-05],
       [3.05406596e-05],
       [2.98548241e-05],
       [3.14931912e-05],
       [3.06927658e-05],
       [2.96285752e-05],


In [113]:
words_phi.shape

(50, 186)

In [119]:
words_phi

array([[7.42036857e-07, 4.11896984e-07, 5.28260342e-07, ...,
        7.28611274e-07, 4.41807895e-07, 6.35449700e-07],
       [5.12994183e-07, 5.78814325e-07, 5.89378655e-07, ...,
        6.24695509e-07, 5.84597176e-07, 8.11475227e-07],
       [5.50612785e-07, 6.56414465e-07, 4.65683323e-07, ...,
        4.73872989e-07, 3.98069558e-07, 4.93535176e-07],
       ...,
       [4.54692543e-07, 5.69792712e-07, 4.85512902e-07, ...,
        4.93324047e-07, 6.24083490e-07, 4.39890357e-07],
       [6.48222631e-07, 2.70797008e-07, 7.86378148e-07, ...,
        7.36495718e-07, 5.86930838e-07, 4.82378920e-07],
       [8.58406952e-07, 8.05897731e-07, 7.00979081e-07, ...,
        9.51214641e-07, 8.20654509e-07, 8.32231066e-07]])

In [118]:
words_phi/sum_of_phis_for_each_words

array([[0.02478591, 0.01353489, 0.0173754 , ..., 0.02444149, 0.01475051,
        0.02098804],
       [0.0171353 , 0.01901977, 0.01938569, ..., 0.0209556 , 0.01951777,
        0.02680192],
       [0.01839186, 0.0215697 , 0.01531714, ..., 0.01589622, 0.01329023,
        0.01630079],
       ...,
       [0.01518788, 0.01872332, 0.01596937, ..., 0.01654871, 0.02083609,
        0.01452898],
       [0.02165227, 0.00889836, 0.02586535, ..., 0.02470598, 0.01959568,
        0.01593232],
       [0.02867296, 0.0264817 , 0.02305642, ..., 0.03190879, 0.02739895,
        0.02748746]])

In [117]:
(words_phi/sum_of_phis_for_each_words).shape

(50, 186)

In [121]:
words_phi_normalization

array([[0.02478591, 0.01353489, 0.0173754 , ..., 0.02444149, 0.01475051,
        0.02098804],
       [0.0171353 , 0.01901977, 0.01938569, ..., 0.0209556 , 0.01951777,
        0.02680192],
       [0.01839186, 0.0215697 , 0.01531714, ..., 0.01589622, 0.01329023,
        0.01630079],
       ...,
       [0.01518788, 0.01872332, 0.01596937, ..., 0.01654871, 0.02083609,
        0.01452898],
       [0.02165227, 0.00889836, 0.02586535, ..., 0.02470598, 0.01959568,
        0.01593232],
       [0.02867296, 0.0264817 , 0.02305642, ..., 0.03190879, 0.02739895,
        0.02748746]])

In [105]:
len(words_phi.sum(axis=0))

186

In [ ]:
numpy.

In [83]:
expElogthetad*expElogbetad

ValueError: operands could not be broadcast together with shapes (50,) (50,186) 

In [88]:
expElogbetad

array([[6.70995809e-05, 3.72462834e-05, 4.77685808e-05, ...,
        6.58855563e-05, 3.99510136e-05, 5.74613083e-05],
       [4.59269769e-05, 5.18196755e-05, 5.27654713e-05, ...,
        5.59272934e-05, 5.23373985e-05, 7.26491746e-05],
       [6.04090452e-05, 7.20168006e-05, 5.10912309e-05, ...,
        5.19897388e-05, 4.36731630e-05, 5.41469243e-05],
       ...,
       [4.22328270e-05, 5.29235797e-05, 4.50954887e-05, ...,
        4.58210047e-05, 5.79662246e-05, 4.08579680e-05],
       [5.44259365e-05, 2.27366032e-05, 6.60257219e-05, ...,
        6.18375035e-05, 4.92797675e-05, 4.05014006e-05],
       [5.15867770e-05, 4.84311858e-05, 4.21260004e-05, ...,
        5.71641429e-05, 4.93180083e-05, 5.00137125e-05]])

In [80]:
expElogthetad* expElogbetad[:,0]

array([7.42036857e-07, 5.12994183e-07, 5.50612785e-07, 4.39498506e-07,
       6.02446092e-07, 6.23093186e-07, 4.36995308e-07, 6.30441942e-07,
       7.08833216e-07, 8.20887782e-07, 4.92940672e-07, 7.75584721e-07,
       6.55726867e-07, 4.03271880e-07, 5.46715188e-07, 5.44132609e-07,
       5.27326752e-07, 4.74211468e-07, 5.26847385e-07, 6.14071078e-07,
       5.35164426e-07, 7.43912824e-07, 5.63956867e-07, 8.26854753e-07,
       7.07725584e-07, 6.60687608e-07, 5.27629852e-07, 5.01769043e-07,
       5.69239178e-07, 5.31869765e-07, 6.50004584e-07, 5.10963081e-07,
       7.35811028e-07, 5.45581685e-07, 4.74899799e-07, 6.78435629e-07,
       5.55873157e-07, 4.40995442e-07, 6.94034758e-07, 6.52717203e-07,
       7.28713922e-07, 6.38794230e-07, 6.94874961e-07, 4.64363532e-07,
       5.07612309e-07, 7.13385545e-07, 4.91993994e-07, 4.54692543e-07,
       6.48222631e-07, 8.58406952e-07])

In [82]:
expElogbetad.shape

(50, 186)

In [51]:
expElogbetad.shape

(50, 186)

In [57]:
ids

[0,
 6144,
 3586,
 3,
 4,
 1541,
 8,
 10,
 3927,
 12,
 4621,
 527,
 9232,
 1112,
 20,
 2587,
 6172,
 10269,
 37,
 42,
 3117,
 1582,
 1585,
 435,
 9268,
 571,
 60,
 61,
 63,
 64,
 5185,
 11,
 4683,
 590,
 1103,
 592,
 5718,
 1623,
 1624,
 89,
 6234,
 8802,
 1638,
 103,
 600,
 9404,
 106,
 3691,
 720,
 2672,
 113,
 2165,
 5751,
 123,
 1148,
 128,
 1670,
 4231,
 1167,
 144,
 147,
 149,
 3735,
 5272,
 1732,
 673,
 5282,
 27,
 1700,
 9893,
 166,
 167,
 173,
 174,
 2224,
 2248,
 372,
 186,
 4284,
 3450,
 117,
 203,
 2244,
 5320,
 201,
 4215,
 9932,
 207,
 208,
 8914,
 7898,
 733,
 1760,
 1744,
 744,
 234,
 1259,
 4287,
 7254,
 249,
 8311,
 5884,
 298,
 254,
 767,
 2304,
 4876,
 270,
 557,
 786,
 789,
 2331,
 287,
 5409,
 290,
 5923,
 2854,
 1834,
 303,
 3888,
 817,
 9523,
 334,
 1333,
 311,
 1855,
 1417,
 325,
 1870,
 1361,
 1362,
 6995,
 342,
 343,
 344,
 857,
 5469,
 351,
 1377,
 2402,
 487,
 884,
 885,
 890,
 4477,
 3455,
 1410,
 5099,
 4489,
 395,
 2570,
 152,
 404,
 1429,
 1430,
 3992,


In [ ]:
numpy.reshape()

In [53]:
expElogbetad[:,0]*2

array([6.70995809e-05, 4.59269769e-05, 6.04090452e-05, 4.32867249e-05,
       4.91224765e-05, 5.47069756e-05, 4.42898492e-05, 5.07696683e-05,
       5.67404420e-05, 6.35409348e-05, 3.98247868e-05, 6.43956300e-05,
       6.12674443e-05, 4.59234664e-05, 5.97317604e-05, 6.06056922e-05,
       6.06392434e-05, 5.49053913e-05, 4.43994595e-05, 6.12795452e-05,
       4.34621733e-05, 5.64724505e-05, 4.34108251e-05, 5.91372126e-05,
       5.26821952e-05, 6.40490212e-05, 4.19222816e-05, 5.21245642e-05,
       5.13633680e-05, 4.50120671e-05, 5.84338152e-05, 4.15962474e-05,
       5.73671952e-05, 5.19036496e-05, 3.97730567e-05, 6.57855500e-05,
       5.45308195e-05, 5.10806025e-05, 6.07964228e-05, 4.62464302e-05,
       4.84325099e-05, 5.96036241e-05, 4.94977324e-05, 4.63975864e-05,
       4.43871811e-05, 7.12804123e-05, 6.60635062e-05, 4.22328270e-05,
       5.44259365e-05, 5.15867770e-05])

In [89]:
a=numpy.array([1,2,3])

In [58]:
len(ids)

186

In [59]:
len(list(set(ids)))

186

In [67]:
gammad

array([0.80818243, 0.99173105, 0.92937133, 1.01810955, 1.27011777,
       0.87797297, 0.93021217, 0.94623241, 0.98542104, 0.97302616,
       1.03712878, 0.89547098, 0.92699843, 1.02500066, 0.91792125,
       0.971065  , 1.06886081, 1.05845946, 1.01193525, 1.14168643,
       0.94179683, 0.956522  , 1.03694447, 0.96105937, 0.94344234,
       1.17071208, 0.87021271, 1.06758464, 0.98247865, 1.14712885,
       1.14920571, 0.96872152, 1.0530657 , 0.97158982, 1.26966729,
       0.96688974, 1.00698621, 0.83450302, 1.16039304, 1.23614038,
       0.80647543, 1.00566718, 0.87828266, 1.07915339, 1.0290761 ,
       0.91197793, 0.90597072, 0.91935529, 0.96605832, 0.9939127 ])

In [91]:
a=numpy.array([1,2,3])
a

array([1, 2, 3])

In [92]:
b=numpy.array([[1,2,3],[4,5,6],[1,2,4]])
b

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 4]])

In [96]:
a.reshape(-1,1)

array([[1],
       [2],
       [3]])

In [97]:
a.reshape(-1,1)*b

array([[ 1,  2,  3],
       [ 8, 10, 12],
       [ 3,  6, 12]])

In [87]:
a.T*b

ValueError: shapes (3,1) and (3,3) not aligned: 1 (dim 1) != 3 (dim 0)

In [77]:
numpy.array([1,4,2]) * numpy.array([2,5,10])

array([ 2, 20, 20])

In [75]:
a[0]

matrix([[1, 2, 3]])

In [74]:
a[0]*b[:,0]

matrix([[12]])

In [71]:
a*b[:,0]

matrix([[12]])

In [ ]:
numpy.

In [68]:
a*b

matrix([[12, 18, 27]])

In [ ]:
gammad

In [56]:
LDA_Model._lambda.shape

(50, 10473)

In [66]:
LDA_Model._lambda

array([[0.94631201, 0.84581722, 1.01871631, ..., 0.99217455, 0.8360095 ,
        1.09406908],
       [0.99463475, 1.05708814, 1.19491775, ..., 0.91939829, 1.00709301,
        0.93445162],
       [0.99751395, 0.97853242, 1.04460572, ..., 0.96534723, 1.02873342,
        1.12321118],
       ...,
       [0.95187171, 1.18101426, 1.02821443, ..., 0.99636862, 0.86653754,
        0.89400902],
       [1.08117387, 1.01755847, 1.00978653, ..., 1.02169988, 0.89065601,
        0.97971279],
       [1.08391883, 1.08849737, 0.97557978, ..., 0.79568456, 0.80195397,
        1.07915967]])

In [61]:
# 요렇게 단어별 토픽에대해 쫘르륵 
expElogbetad[:,0]
expElogbetad[:,1]

array([4.89446813e-05, 5.31249955e-05, 5.34318597e-05, 4.63404859e-05,
       3.70336718e-05, 3.44710120e-05, 5.65652355e-05, 6.14723162e-05,
       5.03267313e-05, 5.17097365e-05, 5.16420208e-05, 5.02961961e-05,
       4.90834036e-05, 4.98286185e-05, 5.11096664e-05, 4.64006936e-05,
       5.42996572e-05, 3.65751585e-05, 6.07862087e-05, 5.84451626e-05,
       4.43686955e-05, 5.94298131e-05, 4.55577160e-05, 5.20172345e-05,
       6.42983857e-05, 5.68783225e-05, 3.65961100e-05, 6.53091538e-05,
       4.59326212e-05, 6.99558642e-05, 3.90991915e-05, 4.23329032e-05,
       6.45137350e-05, 5.19450275e-05, 6.27137851e-05, 5.39694809e-05,
       5.35833875e-05, 6.90929254e-05, 5.21153716e-05, 5.55719712e-05,
       4.42467940e-05, 4.86512919e-05, 5.16753137e-05, 4.29372049e-05,
       5.97266604e-05, 4.33834402e-05, 5.00058114e-05, 4.92893115e-05,
       6.08785971e-05, 6.10640861e-05])